import{a as p,i as a,S as y}from"./assets/vendor-31f4717e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();const L="https://pixabay.com/api/",B="45213588-1347783919d0c1f7f1631233d";async function m(t,r){const n={key:B,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:r};try{const i=await p.get(L,{params:n});return i.data&&Array.isArray(i.data.hits)?i.data:(a.error({title:"Error",message:"Unexpected API response format.",position:"topRight"}),{hits:[]})}catch(i){return a.error({title:"Request error",message:`Something went wrong: ${i.message}`,position:"topRight"}),{hits:[]}}}const b=document.querySelector(".gallery");function v({webformatURL:t,largeImageURL:r,tags:n,likes:i,views:e,comments:s,downloads:l}){return`<li class="gallery-card"> 
    <figure class="image-container">
      <a href="${r}">
        <img class="image-thumbnail" src="${t}" alt="${n}" title="" width="360" height="200"/>
      </a>
      <figcaption class="image-details">
        <ul class="details-list">
          <li class="details-item">Likes<p class="details-count">${i}</p></li>
          <li class="details-item">Views<p class="details-count">${e}</p></li>
          <li class="details-item">Comments<p class="details-count">${s}</p></li>
          <li class="details-item">Downloads<p class="details-count">${l}</p></li>
        </ul>
      </figcaption>
    </figure>
  </li>`}function w(t){return t.map(v).join("")}function f(t){const r=w(t);b.innerHTML+=r}const o={btnSearch:document.querySelector(".btn-search"),form:document.querySelector(".form"),input:document.querySelector("input"),ul:document.querySelector("ul.gallery"),loadBtn:document.querySelector(".load-btn")};let c=1,d="",h=new y(".gallery a");o.loadBtn.classList.add("hiddenBtn");o.form.addEventListener("submit",async t=>{try{if(o.loadBtn.classList.remove("hiddenBtn"),t.preventDefault(),d=o.input.value.trim(),d===""){a.error({title:"Error",message:"Please enter a search query"});return}o.ul.innerHTML="",c=1,g();const r=await m(d,c);u(),r.hits.length===0?(a.error({title:"No results",message:"No images found. Please try a different query."}),o.loadBtn.classList.add("hiddenBtn")):(f(r.hits),h.refresh(),r.hits.length<15?o.loadBtn.classList.add("hiddenBtn"):o.loadBtn.classList.remove("hiddenBtn"))}catch{u(),a.error({title:"Error",message:"Something went wrong."})}});o.loadBtn.addEventListener("click",async()=>{c+=1,console.log("Page incremented:",c),g();const t=await m(d,c);u(),t.hits.length===0?(o.loadBtn.classList.add("hiddenBtn"),a.info({title:"No more results",message:"We're sorry, but you've reached the end of search results."})):(f(t.hits),h.refresh(),t.hits.length<15&&(o.loadBtn.classList.add("hiddenBtn"),a.info({title:"No more results",message:"We're sorry, but you've reached the end of search results."}))),S()});function S(){window.scrollTo({top:document.body.scrollHeight,behavior:"smooth"})}function g(){o.loadBtn.insertAdjacentHTML("afterend",'<div id="loader" class="loader"></div>')}function u(){document.querySelector(".loader").remove()}
//# sourceMappingURL=commonHelpers.js.map
